### PR TITLE
Create Answer

### PR DESCRIPTION
**Pull request by tangshanzhang**
[open_automation_quiz-master.zip](https://github.com/alaahong/open_automation_quiz/files/4352731/open_automation_quiz-master.zip)

### CODE REVIEW

**Comment by alaahong** [comment]
> [open_automation_quiz-master.zip](https://github.com/alaahong/open_automation_quiz/files/4352731/open_automation_quiz-master.zip)

Thanks for your efforts, please make sure you can execute below command with successful result at your local part!

`mvn test`

**Comment by tangshanzhang** [comment]
[open_automation_quiz-master.zip](https://github.com/alaahong/open_automation_quiz/files/4359844/open_automation_quiz-master.zip)

**Comment by alaahong** [comment]
> [open_automation_quiz-master.zip](https://github.com/alaahong/open_automation_quiz/files/4359844/open_automation_quiz-master.zip)

**The last time to mention that:**

1. Please follow the quiz **requirements**, we don't need any baidu case:
https://github.com/alaahong/open_automation_quiz

2. Please do not throw a semi-manufactures, there are many conflicts in your project；
image

3. Please make sure your project can be compiled, `mvn compile` , we will also run  `mvn test` to check your feasibility;
image

4. For now, we need the high-intermediate level candidate, please do better to present your professional implementation;

5. Caused by seems you don't know how to resolve the commits as quiz mentioned, please submit your complted quiz project before next Monday (Mar-23), otherwise, we might treat you as given up.

Any confuse please raise an issue or contact with your vendor;

**Comment by tangshanzhang** [comment]
image
Which version is your maven ？

Due to the network problem, I can't access the test address, so I changed it to https://cn.bing.com/

**Comment by tangshanzhang** [comment]
[open_automation_quiz-master.zip](https://github.com/alaahong/open_automation_quiz/files/4362497/open_automation_quiz-master.zip)

**Comment by tangshanzhang** [comment]
image

**Comment by tangshanzhang** [comment]
image

**Comment by alaahong** [comment]
> image
> Which version is your maven ？
> 
> Due to the network problem, I can't access the test address, so I changed it to https://cn.bing.com/

Thanks for your updates again, let me figure out the missed points for you.

I believe you've got the quiz requirements https://github.com/alaahong/open_automation_quiz , but you didn't  follow the requests as below:

1.  Just highlight the the part 0 missed.  I don't know why you upload the zip again and again, even I mention so many times to follow the requirements. 
image

2. Relate to your question with Maven version, 3.6.1 is fine to build your project, but you didn't provide a completed project with maven build. I believe you also find out the root cause by your remove action.
image
image

And meanwhile, you still leave so many conflicts after I highlight the detail.
image

3. If you **can not** open the target URL of quiz 1, why you accept the alert?  Both baidu & bing won't alert you, but target URL of quiz 1 need.
image

4. Where is IE implementation? I can find out any words from you.

5. As above mentioned, I will execute mvn test to check your result, but there is only quiz 1 triggered. 
image

6. Even we check the detail of your code, you still not provide more experienced implementation.
image
image
image
image
...... more


So, you can not understand the quiz requirements and complete the quiz with most check points,  and meanwhile, you didn't present more professional skill so far.
Just as we mentioned:
image

Thanks for your efforts.

**Pull request closed without merging**
